// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBl4kf61bI9ESMsc2JM2H_m0CQtpskUFs',
    appId: '1:301307000588:web:033c0c8681a76e621f3b29',
    messagingSenderId: '301307000588',
    projectId: 'wellbeing-journey-b4dbd',
    authDomain: 'wellbeing-journey-b4dbd.firebaseapp.com',
    storageBucket: 'wellbeing-journey-b4dbd.firebasestorage.app',
    measurementId: 'G-LGYCWYVKHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATj_wBHSJRAztAM6_VMKmAEwvt-yfUs-M',
    appId: '1:301307000588:android:8caa70fdefa3868f1f3b29',
    messagingSenderId: '301307000588',
    projectId: 'wellbeing-journey-b4dbd',
    storageBucket: 'wellbeing-journey-b4dbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXdmslQrE2cAG3EGoqaHGJkvZMgwkDi_Q',
    appId: '1:301307000588:ios:5627fb8c75ce979c1f3b29',
    messagingSenderId: '301307000588',
    projectId: 'wellbeing-journey-b4dbd',
    storageBucket: 'wellbeing-journey-b4dbd.firebasestorage.app',
    iosBundleId: 'com.example.wellbeingJourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXdmslQrE2cAG3EGoqaHGJkvZMgwkDi_Q',
    appId: '1:301307000588:ios:5627fb8c75ce979c1f3b29',
    messagingSenderId: '301307000588',
    projectId: 'wellbeing-journey-b4dbd',
    storageBucket: 'wellbeing-journey-b4dbd.firebasestorage.app',
    iosBundleId: 'com.example.wellbeingJourney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBl4kf61bI9ESMsc2JM2H_m0CQtpskUFs',
    appId: '1:301307000588:web:24548debfec3bac41f3b29',
    messagingSenderId: '301307000588',
    projectId: 'wellbeing-journey-b4dbd',
    authDomain: 'wellbeing-journey-b4dbd.firebaseapp.com',
    storageBucket: 'wellbeing-journey-b4dbd.firebasestorage.app',
    measurementId: 'G-FLJ6KEJ9D4',
  );
}
